### ISSUE TITLE
"Find screeencasts" button not working

### ISSUE THREAD

**Issue by MaxTheMonster** [alexbooker/communitycasts.co#10]
The "Find screencasts" button does not work on pages other than the main page. For example: 
On the about page, if you click it, it scrolls down instead of actually showing you courses.

Thanks,

**Comment by alexbooker** [comment]
Proposed solution: When the user clicks the *"Find screencasts"* button they will redirected to the screencasts page.

Sound good?

**Comment by MaxTheMonster** [comment]
Sounds great! Thanks.

**Comment by alexbooker** [comment]
I'll get it done this weekend unless you want to submit a pull request before then :wink:.

**Comment by MaxTheMonster** [comment]
I'll see what I can do.

**Comment by alexbooker** [comment]
Fixed in facaaac5e3c2e8a979a3336e0d23f6657d70c6d1

Note: Changes are not yet live.

**Comment by alexbooker** [comment]
Fix is now live :tada:!
