### ISSUE TITLE
Scroll to Top Button Position is Incorrect

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/communitycasts.co#17]
Scroll to top button should be at the bottom of the menu!

![](https://i.imgur.com/7RV1EB7.png)

At the moment it is beneath the `menu-content`. It should be at the bottom of it's container: `menu-inner`.

This *used* to work so evidently I have introduced a regression somewhere.

**Comment by artrmz** [comment]
Try adding position: relative; to .menu
and position: absolute; to .menu .menu-inner
That's what worked for me ;)
http://i.imgur.com/MqlN6kZ.png
But no idea if it's actually a proper way to do that ;)

**Comment by alexbooker** [comment]
@artrmz I'll try this out soon. Thanks!

**Comment by alexbooker** [comment]
Does not work, unfortunately.

**Comment by alexbooker** [comment]
Closed by f7aaafba7322fc190d024bfea01d10d6cab7430b
