### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/communitycasts.co#23]
- Should use colours from Community Casts:

    ```sass
    $accent-color: #4EB15F;
    $dark-accent-color: #349851;
    $very-dark-accent-color: darken($dark-accent-color,10%);
    $text-color: #212121;
    $icon-color: $text-color;
    ```

- Should use `Roboto Mono` font like the [logo](https://github.com/alexbooker/communitycasts.co/blob/master/source/client/scss/base/_variables.scss#L33) (I am flexible on this if `Roboto Mono` looks bad at a low resoloution).

- Should be flat (i.e. no bevels or shadow).

- Should have the text **CC** as in **C**ommunity **C**asts.

**Comment by alexbooker** [comment]
![](https://i.imgur.com/G3VB2KJ.png)

[*Album*](https://imgur.com/a/RFcp7#5)

**Comment by kovv** [comment]
Always want to create icon with squares only :) Use it if you like it.
![cc_logo](https://cloud.githubusercontent.com/assets/9194394/10263412/eeff54fc-6a0f-11e5-873b-d6f1ec946a5d.png)
Icon and source: https://drive.google.com/file/d/0B6YPFOgOCi-BdWdwRUw4NUNDQ2M/view?usp=sharing

**Comment by alexbooker** [comment]
_Perfect._

**Comment by alexbooker** [comment]
If you go to http://communitycasts.co/ in Chrome, you should see the fav icon! _Awesome_ work @kovv.

**Comment by kovv** [comment]
Wow. That was fast. ;)
