### ISSUE TITLE
Some Features

### ISSUE THREAD

**Issue by Evinon** [alexbooker/communitycasts.co#39]
# Tab Feature

How about the Idea of enabling users to open a Screencast on a new Tab?
**Why?**

- When a User has used the Search function, then he will see the Standard page without the results of the search function, when clicking the Back on the Screencast page. :-1: 

- If a User has loaded more Screencasts and scrolled down the Page he will see the standard page when clicking the Back button after seeing a Screencast. :-1: 

- The same happens for the Tag-Page :-1: 

Add **$event** as a parameter to the **renderScreencast** function and open the Screencast on a new Tab if $event.**which** is equal to **2**. (Middle mouse button)

# Copy Link

Make it possible to copy a the Link of a Screencasts without actually opening it.

*This was written where I already should be sleeping, so you might see some grammatical mistakes :)*

**Comment by alexbooker** [comment]
Hi @Evinon, Long time no see!

I think these are both *excellent* short term* solutions. Do you want to have a stab at implementing them?

* Short term because ideally the app will remember the previous state and scroll position, sort of like Android apps do.

**Comment by Evinon** [comment]
Hi @alexbooker.
I would like to implement those features but currently some projects and study take much time.
Maybe there is someone else who want to help building this Application? I can't be the only one :smile:

**Comment by alexbooker** [comment]
@Evinon, 

I don't think these improvements will take much time to implement, to be honest.

I'll probably do it some time soon.

**Comment by Evinon** [comment]
@alexbooker  Yes those short term solutions aren't that hard but making the app remember it's previous state as you described is a bit hard, at least for me. (well it looks like so because I don't know really much about the "state"-system behind angular.)

**Comment by alexbooker** [comment]
@Evinon,

I get you now. 

I was refering to the temporary solutions. If you want to have a stab at them, be my guest  :smile:! Otherwise, it's OK, I'll do it myself when I have time.
