### ISSUE TITLE
Mobile Responsiveness/Icon Compatibility

### ISSUE THREAD

**Issue by jgetrost** [alexbooker/communitycasts.co#9]
Icons are not appearing on my android device.

Samsung Galaxy Note 3
Android 4.4
Android Browser
![2015-09-01 17 48 33](https://cloud.githubusercontent.com/assets/14022926/9612190/cf30a1aa-50a9-11e5-9a09-60ed85bfe2f7.png)

**Comment by alexbooker** [comment]
Thanks, James. I'll look into this when I tackle the mobile UI.

**Comment by alexbooker** [comment]
There is a good chance is fixed now. When you get a minute, can you check to see if it's fixed? Thanks in advance.

**Comment by jgetrost** [comment]
The icons are there now and look great. The only other problem on mobile is the text wrapping for the title of the screencasts.

**Comment by alexbooker** [comment]
That is because I have made **zero**  effort to make website work on mobile *yet*. I'll get on top of that soon.
